<div class="sidebar">
    <div class="sidebar-link">
    	<a href="/admin/schedule"><div><p><i class="fa fa-book side-header-icon"></i><span class="side-name">Schedules
        	<span class="arrow-right" hidden="true"></span></p></div></a>
    	<a href="/admin/list"><div><p><i class="fa fa-folder-open-o side-header-icon"></i><span class="side-name">Class Lists
        	<span class="arrow-right" hidden="true"></span></p></div></a>
    	<a href="/admin/students"><div><p><i class="fa fa-users side-header-icon"></i><span class="side-name">Students
        	<span class="arrow-right" hidden="true"></span></p></div></a>
    	<a href="/admin/professors"><div><p><i class="fa fa-bank side-header-icon"></i><span class="side-name">Professors
        	<span class="arrow-right" hidden="true"></span></p></div></a>
    	<a href="/admin/grade"><div><p><i class="fa fa-bar-chart-o side-header-icon"></i><span class="side-name">Report of Grades
        	<span class="arrow-right" hidden="true"></span></p></div></a>
    	<a href="/admin/request"><div><p><i class="fa fa-mail-forward side-header-icon"></i><span class="side-name">Transfer Requests
        	<span class="arrow-right" hidden="true"></span></p></div></a>
    	<a href="/accounts/account"><div style="border-bottom: 1px solid rgba(256, 256, 256, 0.6);"><p>
        	<i class="fa fa-gears side-header-icon"></i><span class="side-name">Account Settings
            <span class="arrow-right" hidden="true"></span></p></div></a>
    </div>
    <div class="sidebar-show">
    	<span class="minimize"><i class="fa fa-arrow-circle-left side-btn"></i></span>
    </div>
    <div class="sidebar-show">
	    <span class="maximize" hidden="true"><i class="fa fa-arrow-circle-right side-btn"></i></span>
	</div>
</div>
<div class="home-body-max">
	<span style="margin: 10px 10px 0 0; font-size:36px"><i class="fa fa-book"></i></span>
	<p class="schedule-title" style="display: inline">Schedules</p>
     
     <!--POP OVER TITLE (GENERAL) -->
     <div class="popover-title" style="display:none">Tip <span style="color:#F00"><i class='fa fa-exclamation-circle'>
     	</i></span></div>
         
     <!--POP OVER MESSAGE (GENERAL) -->
     <div class="popover-message" style="display:none">Edit and Save revisions to subject information by clicking them!</div>   
     
    <div class="schedule-container">
    	<div class="panel panel-default panel-schedule" data-toggle="popover" data-placement="top" data-trigger="hover">
         <?php if(!empty($schedule)): ?>
	         <button id="print-acc" type="button" class="btn btn-default" data-toggle="tooltip" data-placement="top" 
             	style="float:right; margin: 6px 15px 0 0;" title="Print Schedule"><i class="fa fa-print"></i></button>
		<?php endif; ?>
    	     <button id="create-acc" type="button" class="btn btn-default" data-toggle="modal" data-target="#add-schedule"
             	data-placement="top" style="float:right; margin: 6px 10px 0 0;" title="Add Schedule">
                    	<i class="fa fa-plus-circle"></i></button>
        	<div class="panel-heading container-fluid" style="background: rgba(0,102,255,0.8);">
	            <div class="col-md-1 col-heading">CODE</div>
	            <div class="col-md-3 col-heading">SUBJECT</div>
	            <div class="col-md-2 col-heading">DAY</div>
	            <div class="col-md-3 col-heading">TIME</div>
	            <div class="col-md-2 col-heading">FACULTY</div>
			</div>
				<?php $flag = 0; foreach($schedule as $key => $values): ?>
                	<?php if(($flag == 0) && ($values['subject_active'] != 0)): $flag++; ?>
                    	 <div class="panel-schedule-body container-fluid" 
                         	style="background: rgba(0,0,0,0.1)" data-toggle="modal" data-target="#edit-schedule">
                           <div class="col-md-1 col-body schedule-id"><?php echo $values['subject_id'] ?></div>
		            	   <div class="col-md-1 col-body schedule-code"><?php echo $values['subject_code'] ?></div>
	        	    	   <div class="col-md-3 col-body schedule-name"><?php echo $values['subject_name'] ?></div>
	    	        	   <div class="col-md-2 col-body schedule-day"><?php echo ucfirst($values['subject_day']) ?></div>
	        	    	   <div class="col-md-3 col-body schedule-time"><?php echo $values['subject_time'] ?></div>
	            		   <div class="col-md-2 col-body schedule-faculty"><?php echo $values['user_name'] ?></div>
                           <div class="col-md-1 col-body close"><span class="schedule-delete" data-toggle="tooltip" 
                           		data-placement="right" title="Delete">&times;</span></div>
            			</div>
                    <?php elseif(($flag == 1) && ($values['subject_active'] != 0)): $flag--; ?>
	                	 <div class="panel-schedule-body container-fluid" data-toggle="modal" data-target="#edit-schedule">
                           <div class="col-md-1 col-body schedule-id"><?php echo $values['subject_id'] ?></div>
		            	   <div class="col-md-1 col-body schedule-code"><?php echo $values['subject_code'] ?></div>
	        	    	   <div class="col-md-3 col-body schedule-name"><?php echo $values['subject_name'] ?></div>
	    	        	   <div class="col-md-2 col-body schedule-day"><?php echo ucfirst($values['subject_day']) ?></div>
	        	    	   <div class="col-md-3 col-body schedule-time"><?php echo $values['subject_time'] ?></div>
	            		   <div class="col-md-2 col-body schedule-faculty"><?php echo $values['user_name'] ?></div>
                           <div class="col-md-1 col-body close"><span class="schedule-delete" data-toggle="tooltip" 
                           		data-placement="right" title="Delete">&times;</span></div>
            			</div>
                    <?php endif; ?>
				<?php endforeach; ?>
            
        </div>
	</div>
</div>

<!--ADD SCHEDULE MODAL -->

<div class="modal fade" id="add-schedule" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="background: rgba(51,204,51,0.7); color: #FFF">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">
        	<span class="side-header-icon"><i class="fa fa-plus-circle fa-4"></i></span>
			<strong> Add Schedule</strong>
        </h4>
      </div>
      <div class="modal-body"> 
      	<form action="/admin/schedule" method="post">
        	<input name="post-flag" value="add" hidden="true"/>
        	<p class="edit-title">Subject Code:</p>
        	<input class="form-control edit-input" name="add-schedule-code" required="required" />
            <p class="edit-title">Subject Name:</p>
            <input class="form-control edit-input" name="add-schedule-name" required="required" />
            <p class="edit-title">Subject Day:</p>
            <input class="form-control edit-input" name="add-schedule-day" required="required"  />
            <p class="edit-title">Subject Time:</p>
            <input class="form-control edit-input" name="add-schedule-time" required="required"  />
            <p class="edit-title">Subject Faculty:</p>
            <select class="form-control edit-input" name="add-schedule-faculty" >
            	<?php foreach($instructor as $key => $values): ?>
                	<option value="<?php echo $values['professor_id']; ?>"><?php echo $values['user_name']; ?></option>
                <?php endforeach; ?>
            </select>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success">Save</button>
      </div>
      </form>
    </div>
  </div>
</div>

<!--EDIT SCHEDULE MODAL -->

<div class="modal fade" id="edit-schedule" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="background: rgba(51,204,51,0.7); color: #FFF">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">
        	<span class="side-header-icon"><i class="fa fa-book fa-4"></i></span>
			<strong> Edit Schedule</strong>
        </h4>
      </div>
      <div class="modal-body"> 
      	<form class="edit-schedule" action="/admin/schedule" method="post">
        	<input name="post-flag" value="edit" hidden="true" />
            <input name="schedule-id" hidden="true" />
        	<p class="edit-title">Subject Code:</p>
        	<input class="form-control edit-input" name="schedule-code" required="required" />
            <p class="edit-title">Subject Name:</p>
            <input class="form-control edit-input" name="schedule-name" required="required" />
            <p class="edit-title">Subject Day:</p>
            <input class="form-control edit-input" name="schedule-day" required="required"  />
            <p class="edit-title">Subject Time:</p>
            <input class="form-control edit-input" name="schedule-time" required="required"  />
            <p class="edit-title">Subject Faculty:</p>
            <select class="form-control edit-input" name="schedule-faculty">
            	<option class="option-active"></option>
            	<?php foreach($instructor as $key => $values): ?>
                	<option value="<?php echo $values['professor_id']; ?>"><?php echo $values['user_name']; ?></option>
                <?php endforeach; ?>
            </select>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success">Save</button>
      </div>
      </form>
    </div>
  </div>
</div>

<!--DELETE SCHEDULE MODAL -->

<form class="delete-schedule" action="/admin/schedule" method="post" hidden="true">
	<input name="post-flag" value="delete" hidden="true"/>
	<input name="delete-id" />
    <input name="delete-code" />
    <input name="delete-subject" />
    <input name="delete-day" />
    <input name="delete-time" />
    <input name="delete-faculty" />
    <input type="submit" class="btn-delete-schedule" />
</form>