<style>
@media screen and (max-width: 1000px) {
   .btn-signin {
   		margin-left: 85%;
   }
   .col-md-5 {
   		display: inline;
   }
   .icon-container {
   		display: inline;
		width: 50px;
   }
   .icon-desc {
   		display: none !important;
   }
   .icon-title {
	   	display: inline;
		font-size: 14px;
		width: 100px
   }
   .welcome-icon {
		display: inline;
		height: 47px;
   		width: 50px;
   }
}

@media screen and (min-height: 900px) {
	 .section-footer {
		height: 40%;
	 	margin-top: 30%;
	 }
	 
	 .section-title {
	 	font-size: 65px;
	 }
	 
	 .welcome-subtitle {
   		font-size: 80px;
   	 }
}

@media screen and (max-width: 800px) {
   .welcome-subtitle {
   		font-size: 40px;
   }
   .btn-signin {
   		margin-left: 5%;
   }
}
</style>
<section class="section-1">
	<a href="login"><button class="btn-signin pos">Sign in</button></a>
    <div class="box pos">
	    <div class="box-in pos">
		    <img src="/assets/images/COPERS-head.png" />
            <p class="welcome-subtitle">Your great future,</p>
            <p class="welcome-subtitle">we will secure</p>
	    </div>
    </div>
    <div id="wrapper">
		<div id="container">
			<div id="slider">
        		<img class="slider-image" src="/assets/images/copers2.jpg" />
                <img class="slider-image" src="/assets/images/copers1.jpg" />
            	<img class="slider-image" src="/assets/images/copers3.jpg" />
            </div>
		</div>
	</div>
</section>

<section class="section-2">
    <div class="container-fluid">
    	<h2 class="section-title">Your future, secured with these features</h2>
    	<div class="row">
		    <div class="col-md-1 icon-container">
        		<img class="welcome-icon" src="/assets/icons/png/Book.png" />
        	</div>
        	<div class="col-md-5">
        	    <h3 class="icon-title">New Enrolment Process</h3>
        	    <p class="icon-desc">
	    	        With the provision of this latest installment in the PLM innovation,
    		        we are introducing the new enrolment process of PE subjects from PE electives.</p>
        	</div>
        	<div class="col-md-1 icon-container">
        		<img class="welcome-icon" src="/assets/icons/png/Clipboard.png" />
        	</div>
        	<div class="col-md-5 col-xs-0">
        	    <h3 class="icon-title">Schedule Manager</h3>
        	    <p class="icon-desc">
        	    	The Online PE Enrolment System does not only enrol students but also provides certain admin tweaks that 
        	        COPERS professors can surely utilize. One example is the easy deployment of PE subject and its 
                    related information. 
             	</p>
        	</div>
    	</div>
		<div class="row">
	    	<div class="col-md-1 icon-container">
        		<img class="welcome-icon" src="/assets/icons/png/Retina-Ready.png" />
        	</div>
        	<div class="col-md-5">
        	    <h3 class="icon-title">Accessible Student Record</h3>
        	    <p class="icon-desc">
        	    	Tracking and modifying the students&rsquo; performance are one of the great privileges that this 
        	        innovation can offer. Students taking up PE classes can be easily searched and managed. 
        	    </p>
        	</div>
        	<div class="col-md-1 icon-container">
        		<img class="welcome-icon" src="/assets/icons/png/Mail.png" />
        	</div>
        	<div class="col-md-5">
        	    <h3 class="icon-title">Grading System in New Heights</h3>
            	<p class="icon-desc">
            		As we build stronger connections between COPERS and students, the integration of grading process has
            	    become available in this system. As a student, you are not only available to enrol but track your own 
            	    standing and make a move.  
           	 	</p>
        	</div>
    	</div>
   		<div class="row">
		    <div class="col-md-1 icon-container">
    	    	<img class="welcome-icon" src="/assets/icons/png/Compas.png" />
    	    </div>
    	    <div class="col-md-5">
    	        <h3 class="icon-title">Be in the Right Track</h3>
    	        <p class="icon-desc">
    	        	You can now manage your account based on your preference. We want you to maximize all the possibilities
    	            with this system. Enrol now and make a stand. 
    	        </p>
    	    </div>
    	    <div class="col-md-1 icon-container">
    	    	<img class="welcome-icon" src="/assets/icons/png/Infinity-Loop.png" />
    	    </div>
    	    <div class="col-md-5">
    	       <h3 class="icon-title">A Better World</h3>
    	        <p class="icon-desc">
   		         	At COPERS, your existence is of utmost importance and the devotion to develop this system goes beyond limits.
       		        We consider your experience, we want you.   
            	</p>
        	</div>
    	</div>
    </div>
</section>

<section class="section-3">
	<div class="container-fluid">
		<h2 class="section-title">
	    	What are you waiting for? Try it now.<br />
	    </h2>
	    <h2 class="title-button">
        	<a href="login"><button class="btn btn-primary btn-started">Let's Get Started</button></a>
        </h2>
    </div>
    <div class="section-footer">
    	<h2 class="footer-title">
	    	Made by Team Awesome<br />
	    </h2>
        <div class="container-fluid footer-link-container">
	        <div class="col-md-6 footer-link">
	        	<p class="footer-link-title">COPERS</p>
	    	    <ul class="footer-link-list">
	        		<li>About Us</li>
	        	    <li>FAQs</li>
	        	</ul>
	        </div>
	        <div class="col-md-6 footer-link">
		 		<p class="footer-link-title">CONTACT US</p>
    		    <ul class="footer-link-list">
    	    		<li>(+63) 9066283805</li>
    	            <li>Pamantasan ng Lungsod ng Maynila</li>
    	    	    <li>Rajah Sulayman Gym</li>
    	            <li>copers@gmail.com</li>
    	    	</ul>
    	    </div>
	    </div>
        <p class="footer-link-year">&copy;<?php echo date('Y'); ?> PLM-COPERS&nbsp;&nbsp;&nbsp;
    		<a href="#" class="footer-anchor">Terms</a>
    		<a href="#" class="footer-anchor">Privacy Policy</a>
    		<a href="#" class="footer-anchor">Copyright</a>
        </p>
    </div>
</section>
