<div class="sidebar">
    <div class="sidebar-link">
    	<a href="/schedule"><div><p><i class="fa fa-book side-header-icon"></i><span class="side-name">Schedules
        	</span></p></div></a>
    	<a href="/list"><div><p><i class="fa fa-folder-open-o side-header-icon"></i><span class="side-name">Class Lists
        	</span></p></div></a>
    	<a href="/students"><div><p><i class="fa fa-users side-header-icon"></i><span class="side-name">Students
        	</span></p></div></a>
    	<a href="/professors"><div><p><i class="fa fa-bank side-header-icon"></i><span class="side-name">Professors
        	</span></p></div></a>
    	<a href="/grade"><div><p><i class="fa fa-bar-chart-o side-header-icon"></i><span class="side-name">Report of Grades
        	</span></p></div></a>
    	<a href="/request"><div><p><i class="fa fa-mail-forward side-header-icon"></i><span class="side-name">Transfer Requests
        	</span></p></div></a>
    	<a href="/accounts/account"><div style="border-bottom: 1px solid rgba(256, 256, 256, 0.6);"><p>
        	<i class="fa fa-gears side-header-icon"></i><span class="side-name">Account Settings</span></p></div></a>
    </div>
    <div class="sidebar-show">
    	<span class="minimize"><i class="fa fa-arrow-circle-left side-btn"></i></span>
    </div>
    <div class="sidebar-show">
	    <span class="maximize" hidden="true"><i class="fa fa-arrow-circle-right side-btn"></i></span>
	</div>
</div>