<header>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
   		<div class="navbar-header">
    	  <a class="navbar-brand" href="index">
    	  	<img class="lclogo" src="/assets/images/logo.png" />lco.</a>
    	</div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="logout">Log out</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>